# Generated by Django 6.0 on 2025-12-26 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('publication_year', models.IntegerField()),
                ('genres', models.CharField(blank=True, max_length=255)),
                ('co_authors', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.author')),
            ],
        ),
    ]
